# Generated by Django 2.0.13 on 2019-04-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
